name: Create release with Arabic search support

on:
    create:
        tags:
            - "arabic-search-*"

permissions:
    contents: write
jobs:
    create-release:
        name: Create Release
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              run: bash ci/install-rust.sh stable
            - name: Build
              run: cargo  build --release --features arabic-search
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: target/release/mdbook
